embedder:
  class_path: jmteb.embedders.SentenceBertEmbedder
  init_args:
    add_eos: false
    batch_size: 32
    model_name_or_path: /root/AIMET_ruri/ruri-small-v2
    normalize_embeddings: false
evaluators:
  nlp_journal_abs_intro:
    class_path: jmteb.evaluators.RetrievalEvaluator
    init_args:
      doc_chunk_size: 1000000
      doc_dataset:
        class_path: jmteb.evaluators.retrieval.data.HfRetrievalDocDataset
        init_args:
          dataset_path: /root/jmteb_260326
          id_key: docid
          name: nlp_journal_abs_intro-corpus
          path: sbintuitions/JMTEB
          split: corpus
          text_key: text
      doc_encode_kwargs: {}
      doc_prefix: '文章： '
      force_max_length: false
      log_predictions: false
      query_encode_kwargs: {}
      query_prefix: 'クエリ： '
      test_query_dataset:
        class_path: jmteb.evaluators.retrieval.data.HfRetrievalQueryDataset
        init_args:
          dataset_path: /root/jmteb_260326
          name: nlp_journal_abs_intro-query
          path: sbintuitions/JMTEB
          query_key: query
          relevant_docs_key: relevant_docs
          split: test
      top_n_docs_to_log: 5
      val_query_dataset:
        class_path: jmteb.evaluators.retrieval.data.HfRetrievalQueryDataset
        init_args:
          dataset_path: /root/jmteb_260326
          name: nlp_journal_abs_intro-query
          path: sbintuitions/JMTEB
          query_key: query
          relevant_docs_key: relevant_docs
          split: validation
save_dir: /root/AIMET_ENV/tools/ruri/convert/script/jmteb_result/jmteb_soc_quat/dim_768
overwrite_cache: false
eval_include:
- nlp_journal_abs_intro
truncate_dim: 768
log_predictions: true
pkl_path: /root/AIMET_ENV/tools/ruri/convert/script/result/pooling_quat/
dataset_path: /root/jmteb_260326
